### ISSUE TITLE
[bug] Windows: Credentials don't appear to be saved when first adding a cluster

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#229]
1. Add a new cluster which uses authentication then press Test Cluster in the Add Cluster dialog. The test will succeed and allow you to add the cluster.
2. Now click Connect to open the CQLSH view on this cluster and the view opens but just hangs with no errors or any indication of what it is doing.
3. Go back to the workspace view and click Test Connection on the cluster you just added. It will fail due to missing authentication credentials
4. Modify the cluster configuration to re-add the username and password. Everything now works as expected.

**Comment by millerjp** [comment]
@rgooding this should have been fixed with #200 . Can you confirm which verson of the app you have taken and which version of Windows your on.

@mhmdkrmabd looks like #200 is not quite fixed yet.

**Comment by mhmdkrmabd** [comment]
@millerjp @rgooding this is a test with the latest release `AxonOps.Workbench-0.1.1-internal-20240813-win-x64` and by following the same steps, there're no errors of any kind nor missing credentials, everything works as expected

https://github.com/user-attachments/assets/ff2a3a50-cc7f-4a72-a574-91c5304af695

I recommend to check if the latest release is the one being used already, and you may try to remove old data - can be found in `C:\Users\{user}\axonops-developer-workbench` - as well despite it's mostly not necessary

**Comment by rgooding** [comment]
I can still reproduce this with a fresh install of the 20240820 build on both Windows 10 and 11, it also seems to happen for me on macOS where I have to enter my password about 5 times to unlock the keychain and then it still doesn't connect.

**Comment by mhmdkrmabd** [comment]
@rgooding it's appreciated if you can record a video of what is happening exactly, as this is an non-common behavior as it seems yet we still need to investigate and figure out the cause of this

This is not a must, however I do recommend to perform the following and try again:
- Linux and macOS:
	- Delete the folder(s) with perfix .axonops- in the home folder.
	- In the OS Keychain, remove all keys with prefix AxonOps.
- Windows:
	- Delete the folder with prefix axonops- in the user directory folder C:\Users\{username}.
	- Delete the folder with prefix AxonOps in apps' data folder C:\Users\{username}\AppData\Roaming or %appData%.
	- In the Windows Credential Manager, remove all credentials with prefix AxonOps.
	- In the registries - using the regedit tool -, navigate to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\AxonOpsWorkbenchClustersSecrets - it can also be AxonOpsDeveloperWorkbenchClustersSecrets -, delete the entire key/folder.

**Comment by millerjp** [comment]
@rgooding I will close this now as its invalid/fixed with latest builds and above instructions

**Comment by rgooding** [comment]
I can still reproduce this even after following the steps to clear out the old data. Please see the attached video.

https://github.com/user-attachments/assets/a7723d95-2ab5-4551-887d-0b25615ff31a

**Comment by mhmdkrmabd** [comment]
@rgooding that's a new way added to figure out if connection has been lost with the cluster while creating the work area, it seems it might by false think connection has been lost, I believe this is not a big thing will investigate and do changes for the next PR

**Comment by mhmdkrmabd** [comment]
@rgooding I've done tests with Windows and I can't reproduce the issue, it's appreciated if you can make sure that the connection with that cluster is actually stable, the error you've got is happening when connection is lost with cluster, perhaps it's actually lost, did you try after that error to test connection then connect again?


https://github.com/user-attachments/assets/4f7d21e8-bad8-4f0b-9b3d-f24bad21472e

**Comment by mhmdkrmabd** [comment]
@rgooding it's not about credentials at all, now we need to be sure about the stability of this process, am tuned for your feedback

**Comment by millerjp** [comment]
@mhmdkrmabd so I just saw a demo from @hshimizu and its still not saving the credentials on windows on first time add

**Comment by hshimizu** [comment]
I have just tested [0.1.1-internal-20240826](https://github.com/axonops/axonops-workbench-cassandra/releases/tag/0.1.1-internal-20240826) on Windows 11.


https://github.com/user-attachments/assets/31ba8f19-5c5f-4ac0-94f8-b3999e40ee19

**Comment by digiserg** [comment]
I just tested it on a win10 WM and I have reproduced it.

- Add workspace
- Add cluster
- Enter all the details and hit TEST
- TEST is good and the cluster is saved
- Immediately hit TEST again
- error

![image](https://github.com/user-attachments/assets/58e16ff0-3eb6-4456-87ac-61256a10766f)
